export interface ISinfoTutoria{
    pk1:string
    pk2:string
    periodo:string
    zonal:string
    campus:string
    tipo:string
    programa:string
    bloque:string
    parte_periodo:string
    cod_carrera:string
    carrera:string
    clase:string
    id_alumno:string
    nombre:string
    condicion_acad:string
    fecha_retiro:string
    fecha_matricula:string
    pago:string
}